@startuml diagramaDeClasesMejora2

class InicioDeSesión {
    correo
    contraseña
}

class Usuario {
    nombre
    controlParental
}

class Recomendaciones {
    listaDeVideos
    categoría
}

class Buscador {
    búsqueda
}

class Video {
    resolución
    nombre
    tipo
}

class PistaDeAudio {
    idioma
    calidad
}

class Subtítulos {
    idioma
    color
    tamaño
    fuente
}

class AjustesDeCuenta {
    idioma
    región
    conexión
    métodoDePago
    calidadDeStreaming
}

class Watchlist {
    listaDeVideos
}

class Suscripción {
    plan
    dispositivosPermitidos
}

InicioDeSesión "1" --> "1" Usuario : inicia sesión
Usuario "1" --> "1..*" Recomendaciones : accede
Usuario "1" --> "1" Watchlist : utiliza
Usuario "1" -- "1" AjustesDeCuenta : configura
Usuario "1" --> "1" Buscador : utiliza
Usuario "1" --> "0..*" Video : reproduce

Recomendaciones "1" --> "1..*" Video : incluye
Watchlist "1" --> "0..*" Video : contiene
Buscador "1" --> "1..*" Video : encuentra

Video "1" -- "1..*" PistaDeAudio : tiene
Video "1" -- "0..*" Subtítulos : tiene
Video "1" --> "1" Suscripción : depende

AjustesDeCuenta "1" --> "1" Suscripción : gestiona

@enduml
